apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: proxmox-vault-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  parameters:
    roleName: "kubernetes-auth"
    vaultAddress: "https://vault.lab.local:8200"
    vaultSkipTLSVerify: "true"
    objects: |
      - objectName: "proxmox-token"
        secretPath: "infrastructure/data/proxmox/credentials"
        secretKey: "token"