apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: proxmox-vault-sync
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  secretObjects:
    - secretName: proxmox-csi-credentials
      type: Opaque
      data:
        - objectName: proxmox-token
          key: PROXMOX_TOKEN
  parameters:
    roleName: "kubernetes-auth"
    vaultAddress: "https://vault.lab.local:8200"
    vaultSkipTLSVerify: "true"
    objects: |
      - objectName: "proxmox-token"
        secretPath: "infrastructure/data/proxmox/credentials"
        secretKey: "token"